### ISSUE TITLE
missing copyright information

### ISSUE THREAD

**Issue by ghisvail** [AvtechScientific/ASL#12]
The following files have missing copyright information.

```
./cmake/ASLBuildFunctions.cmake: *No copyright* UNKNOWN
./cmake/ASLBuildOptions.cmake: *No copyright* UNKNOWN
./cmake/ASL.pc.cmake.in: *No copyright* UNKNOWN
./cmake/ASLPaths.cmake: *No copyright* UNKNOWN
./cmake/ASLConfig.cmake.in: *No copyright* UNKNOWN
./doc/Developer-Guide/Doxyfile.cmake.in: *No copyright* UNKNOWN
```

Please consider updating these files with an appropriate copyright header.

**Comment by AvtechScientific** [comment]
1. Is this sentence in COPYRIGHT.md not enough?

https://github.com/AvtechScientific/ASL/blob/master/COPYRIGHT.md

"All files, and specifically the images in doc/Developer-Guide/pics are part of the ASL project and are covered by its license except where stated otherwise (cmake/Modules)."
1. Do you mean that the complete header should be added:

/*
- Advanced Simulation Library http://asl.org.il
- 
- Copyright 2015 Avtech Scientific http://avtechscientific.com
  *
  *
- This file is part of Advanced Simulation Library (ASL).
  *
- ASL is free software: you can redistribute it and/or modify it
- under the terms of the GNU Affero General Public License as
- published by the Free Software Foundation, version 3 of the License.
  *
- ASL is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
- GNU Affero General Public License for more details.
  *
- You should have received a copy of the GNU Affero General Public License
- along with ASL. If not, see http://www.gnu.org/licenses/.
  *
  */

**Comment by AvtechScientific** [comment]
Placed copyright headers everywhere, even in CMakeLists.txt
